company/accounts/urls.py
from .views import SignUpView,Update_ProfileView,LoginView,LogoutView
from django.urls import path, include  # new




urlpatterns = [

    path('accounts/login/', LoginView.as_view(), name='login'),#overriding login url of default auth app.
    path('signup', SignUpView.as_view(), name='sign-up'),
    path('profile/<int:pk>/',Update_ProfileView.as_view(), name='profile'),
    path ('accounts/logout/',LogoutView.as_view() , name='logout'),#overriding logout url of default auth app.
    path('accounts/', include('django.contrib.auth.urls')),#Adding the url of default auth app to use it

]

company/company/urls.py
from django.contrib import admin
from django.urls import include,path
from .views import HomePageView
from django.views.generic.base import TemplateView # new
from django.conf import settings 
from django.conf.urls.static import static 

urlpatterns = [
    # display Custom Admin Login  page
    path('admin/', admin.site.urls),
    path('', HomePageView.as_view(),name='home'), # display home page 
    path('about/', TemplateView.as_view(template_name='about.html'), name='about'),  # display about page
    path('services/', TemplateView.as_view(template_name='services.html'), name='services'),  # display services page
    path('contact/', TemplateView.as_view(template_name='contact.html'), name='contact'),  # display contact page
    path('accounts/', include('accounts.urls'), name='accounts'),  # display Sign up page
    path('', include('employee.urls')),  # displays all employee app pages
]

if settings.DEBUG:
     urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

company/accounts/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.
class UserProfileInfo(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE)
    username = models.CharField(max_length=25,null=True)
    dob = models.DateField(blank=True,null=True)  # If no date is selected then Django saves blank field value.
    city = models.CharField(max_length=25,null=True)
    contactno = models.CharField(max_length=25,null=True)
    portfolio_site = models.URLField(blank=True,null=True)
    image = models.ImageField(null=True,upload_to='images/', default = 'images/None/no-img.jpg',blank=True)
    class Meta:
        permissions = [
            ("save data", "Can save data into database"),
            ("read data", "Can only read data"),
        ]

''' class Profile(models.Model):
    user = models.OneToOneField(User)
    department = models.CharField(max_length=200, default='Home')
    is_patient = models.BooleanField(default=False)
    is_doctor = models.BooleanField(default=True)
 '''

company/accounts/forms.py
from django import forms
from .models import UserProfileInfo


class UserCreateForm(forms.Form):
    contactno = forms.CharField(max_length=30, required=True, help_text='Optional')
    city = forms.CharField(max_length=30, required=True, help_text='Optional')
    dob =  forms.DateField(widget=forms.TextInput(attrs=
                                {
                                    'class':'datepicker'
                                }))  # If no date is selected then Django saves blank field value.
    password = forms.CharField(widget=forms.PasswordInput(), required=True)
    confirm_password = forms.CharField(widget=forms.PasswordInput(), required=True)
    username = forms.CharField(max_length=30, required=True, help_text='Optional')
    first_name = forms.CharField(max_length=30, required=False, help_text='Optional')
    last_name = forms.CharField(max_length=30, required=False, help_text='Optional')
    email = forms.EmailField(max_length=254, required=True,help_text='Enter a valid email address')
    image = forms.ImageField()

class LoginForm(forms.Form):
    username = forms.CharField(label="UserName:", max_length=30)
    password = forms.CharField(label="Password", widget=forms.PasswordInput(), required=True)
    utype = forms.CharField(label="Type", max_length=30)

    # Profile Form
class UserProfileForm(forms.ModelForm):

    dob = forms.DateField(widget=forms.TextInput(attrs=
    {
        'class': 'datepicker'
    }))
    class Meta:
        model =  UserProfileInfo
        fields = [
            'dob',
            'city',
            'contactno',
            'username',
            'portfolio_site',
            'image'
            ]

company/accounts/views.py
from django.shortcuts import render,redirect 
from django.urls import reverse_lazy
from django.views.generic.edit import CreateView,UpdateView
from django.views.generic.detail import DetailView
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.contrib.auth.models import User
from django.shortcuts import render
from django.contrib import auth
import os
from .models import User,UserProfileInfo
from .forms import  UserCreateForm,UserProfileForm,LoginForm
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse, request
from django.urls import reverse
from pathlib import Path
from django.contrib.auth.decorators import login_required
from django.views.generic import View
import pyautogui as pu

# Create your views here.
class SignUpView(View):
   model = User,UserProfileInfo
   #login_url = reverse_lazy('login')
   form_class = UserCreateForm
   template_name = "signup.html"

   def get(self, request, *args, **kwargs):
       form = self.form_class()
       return render(request, self.template_name, {'form': form})


   def post(self, request, *args, **kwargs):
       form = UserCreateForm(request.POST, request.FILES or None)


       if form.is_valid():
           # Cleaned(normalized) data
           city = form.cleaned_data.get('city')
           contact_no = form.cleaned_data.get('contactno')
           date_of_birth = form.cleaned_data.get('dob')
           password = form.cleaned_data.get('password')
           username = form.cleaned_data.get('username')
           email = form.cleaned_data.get('email')
           firstname = form.cleaned_data.get('first_name')
           lastname = form.cleaned_data.get('last_name')
           confirm_password = form.cleaned_data.get('confirm_password')
           image = form.cleaned_data.get('image')


           # check if the password match
           if password == confirm_password:
               if not User.objects.filter(email=email).exists():


                   if  User.objects.filter(username=username).exists():
                       pu.alert("Username already exists.Registration Failed.Try again.")
                       return redirect('sign-up')
                   else:
                       new_user = User.objects.create_user(username=username, password=password, email=email,
                       first_name=firstname, last_name=lastname)
                       new_user.save()
                       user= User.objects.get(username=username)
                       p_form = UserProfileForm()
                       p_form = p_form.save(commit=False)
                       p_form.user = user
                       p_form.dob = date_of_birth
                       p_form.username=username
                       p_form.city = city
                       p_form.contactno = contact_no
                       p_form.image = image
                       p_form.save()
                       pu.alert( text="New User Created Successfully",title="Success")
                       # Create UserProfile model

                       # logged in the user
                       login(request, new_user)
                       pu.alert( text="New User Loggedin susuccessfully",title="Success")                      
                       return redirect('home')
               else:
                   pu.alert('Registration Failed - Try different email address')
                   return redirect('sign-up')

           else:
               pu.alert("password and confirmpassword does not match.Try again")
               return redirect('sign-up')

       else:

           return render(request, self.template_name, {'form': form})



class LoginView(View):
    form_class = LoginForm
    redirect_authenticated_user = True
    # model = UserProfileInfo

    def get(self, request, *args, **kwargs):  # GET Method
        form = self.form_class()
        return (render(request, 'registration/login.html', {'form': form}))  # Renders Login page

    def post(self, request, *args, **kwargs):  # POST Method
        form = LoginForm(request.POST or None)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            utype = form.cleaned_data['utype']
            
            if utype == 'Patient':
                model = UserProfileInfo
                user = authenticate(username=username, password=password)

            if user is not None:

                login(request, user)
                if user.is_active and user.is_superuser:
                    if not User.objects.filter(username=username).exists():
                        new_userprofile= UserProfileInfo.objects.create(user=user,username=username, city= '',contactno='',dob='2010-05-25')
                        new_userprofile.save()# Creating userprofile record for superuser(admin)with default date
                    return redirect("/")  # Redirect to home page
       

                else:
                    if user.is_active:
                        return redirect("/") # Redirect to home page
                    else:
                        return redirect('login')  # Redirect to Login page

            else:
                pu.alert("Wrong Username or Password")
                return redirect('login')

        else:
            return render(request, 'registration/login.html', {'form': form})







class LogoutView(View):
    def get(self, request):
     logout(request)
     return HttpResponseRedirect('/')


@method_decorator(login_required, name='dispatch')
class Update_ProfileView(UpdateView):
    model = User, UserProfileInfo
    # login_url = reverse_lazy('login')
    # user.has_perm('app.close_task')
    form_class = UserProfileForm
    template_name = "userprofile.html"

    def get(self, request, *args, **kwargs):
        form = self.form_class()
        return render(request, self.template_name, {'form': form})

    def post(self, request, *args, **kwargs):
      if request.method == 'POST':
          form = UserProfileForm(request.POST, request.FILES or None)
          if form.is_valid():
              # Cleaned(normalized) data
              uId = form.cleaned_data.get('id')
              city = form.cleaned_data.get('city')
              username = form.cleaned_data.get('username')
              contact_no = form.cleaned_data.get('contactno')
              date_of_birth = form.cleaned_data.get('dob')
              image = form.cleaned_data.get('image')

              userprofile = UserProfileInfo.objects.get(username=username)

              userprofile.city = city
              userprofile.contactno = contact_no
              userprofile.dob = date_of_birth
              userprofile.image = image
              userprofile.save()
              pu.alert(text="New User Profile Updated Successfully", title="Success")
              return HttpResponseRedirect('/')


          else:
              pu.alert(text="Form is not valid.Date might be not in 'YYYY-MM-DD' Format", title="Error")

              return HttpResponseRedirect('/')

      else:
          return HttpResponseRedirect('/')

company/accounts/templates/signup.html
{% extends 'base.html' %}
{% block title %}
    <title>SignUp</title>
{% endblock title %}

{% block content %}

  <script src ="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
  <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
  <link rel="stylesheet" href="/resources/demos/style.css">
  <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
  <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>



    <div class="container">
      <form method="POST" class="post-form" enctype="multipart/form-data">
        {% csrf_token %}
    <div class="container">
    <br>

    <div class="form-group row">
    <label class="col-sm-1 col-form-label"></label>
    <div class="col-sm-4">
    <h3>Register</h3>
    </div>
    </div>
    <!--    {{ form.errors }}
{{ form.non_field_errors }}-->

  <div class="form-group row">
    <label class="col-sm-2 col-form-label">UserName:</label>
    <div class="col-sm-4">
      {{ form.username }}
    </div>
  </div>


    <div class="form-group row">
    <label class="col-sm-2 col-form-label">First Name:</label>
    <div class="col-sm-4">
      {{ form.first_name}}
    </div>
  </div>

    <div class="form-group row">
    <label class="col-sm-2 col-form-label">Last Name:</label>
    <div class="col-sm-4">
      {{ form.last_name }}
    </div>
    </div>


    <div class="form-group row">
    <label class="col-sm-2 col-form-label">Email:</label>
    <div class="col-sm-4">
      {{ form.email }}
    </div>
    </div>

    <div class="form-group row">
    <label class="col-sm-2 col-form-label">Password:</label>
    <div class="col-sm-4">
      {{ form.password}}
    </div>
    </div>

    <div class="form-group row">
    <label class="col-sm-2 col-form-label">ConfirmPassword:</label>
    <div class="col-sm-4">
      {{ form.confirm_password}}
    </div>
    </div>

    <div class="form-group row">
    <label class="col-sm-2 col-form-label">City:</label>
    <div class="col-sm-4">
      {{ form.city}}
    </div>
    </div>

    <div class="form-group row">
    <label class="col-sm-2 col-form-label">ContactNo:</label>
    <div class="col-sm-4">
      {{ form.contactno}}
    </div>
    </div>



    <div class="form-group row">
    <label class="col-sm-2 col-form-label">Date of Birth:</label>
    <div class="col-sm-4">
      {{ form.dob }}
        <i class="fa fa-calendar fa-lg"></i>
    </div>
    </div>

   <div class="form-group row">
    <label class="col-sm-2 col-form-label">Profile Picture:</label>
    <div class="col-sm-4">
      {{ form.image}}
    </div>
   </div>




    <div class="form-group row">
    <label class="col-sm-2 col-form-label"></label>
    <div class="col-sm-4">
    <button type="submit" class="btn btn-info">SignUp</button>
    <a href="/employees" class="btn btn-info">Cancel</a>
    </div>
    </div>

    </div>

</form>
    </div>
{% block scripting %}
<script>
  $( function() {
    $( "#id_dob" ).datepicker({
      changeMonth: true,
      changeYear: true,
      yearRange: '1950:2050',
      dateFormat: 'yy-mm-dd',
      defaultDate:"24-09-2019"
    });
  } );
</script>
 <script>
     $(document).ready(function () {
     $('.dropdown-toggle').dropdown();
     });
</script>
{% endblock %}
{% endblock content %}

company/accounts/templates/userprofile.html
{% extends 'base.html' %}
{% block title %}
    <title>Profile</title>
{% endblock title %}

{% block content %}
<!--<script src ="https://code.jquery.com/jquery-3.3.1.min.js"></script>-->
    <script src ="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>


        <form method="POST" class="post-form" enctype="multipart/form-data" >
        {% csrf_token %}

    <div class="container">
           &emsp;&emsp;&emsp;&emsp;&emsp;&emsp;<img src ="{{ user.userprofileinfo.image.url }}"
            class = "img-fluid rounded-circle" alt = "Responsive Image" width = "175" height = "175">


          {% if user.is_authenticated  and user.is_superuser %}
            <h1><strong>Welcome Admin  </strong> </h1>
          {% else %}
           <h1><strong>Welcome   {{user.first_name}}</strong> </h1>

          
          {% endif %} 
        
       <h2>&emsp;Update Profile Page</h2>
<br>
  <div class="form-group row">

    <div class="col-sm-4">
        <input type="hidden" name="username" id="id_username" required maxlength="15" value="{{user.username }}" />
    </div>
  </div>


 <div class="form-group row">
    <label class="col-sm-3 col-form-label">Id:</label>
    <div class="col-sm-4">
        <label>{{ user.id }} </label>
    </div>
  </div>

  <div class="form-group row">
    <label class="col-sm-2 col-form-label"> City:</label>
    <div class="col-sm-4">
        <input type="text" name="city" id="id_city" required maxlength="15" value="{{user.userprofileinfo.city }}" />
    </div>
  </div>

  <div class="form-group row">
    <label class="col-sm-2 col-form-label">Contact No:</label>
    <div class="col-sm-4">
        <input type="text" name="contactno" id="id_contactno" required maxlength="15" value="{{ user.userprofileinfo.contactno }}" />
    </div>
  </div>



   <div class="form-group">
    <label for="id_dob">  Date of Birth:&emsp;&nbsp;&emsp;&nbsp;&emsp;</label>
    <input type="text" name="dob" id="id_dob" required maxlength="25" value="{{ user.userprofileinfo.dob }}" aria-describedby="passwordHelpInline">
     <span class="input-group-addon"><i class="fa fa-calendar fa-lg"></i></span>
    <big id="textHelpInline" class="text-muted">
        Date Must be YYYY-MM-DD Format.
    </big>
  </div>
  <div class="form-group row">
    <label class="col-sm-2 col-form-label">{{user.first_name}}  Picture:</label>
    <div class="col-sm-4">
      {{ form.image}}
    </div>
   </div>


    <div class="form-group row">
    <label class="col-sm-2 col-form-label"></label>
    <div class="col-sm-4">

    <button type="submit" class="btn btn-info">Update</button>
    <a href="/" class="btn btn-info">Cancel</a>

    </div>
    </div>

    </div>

</form>

{% block scripting %}
<script>
  $( function() {
    $( "#id_dob" ).datepicker({
      changeMonth: true,
      changeYear: true,
      yearRange: '1950:2050',
      dateFormat: 'yy-mm-dd',
      defaultDate:"24-09-2019"
    });
  } );
</script>
 <script>
     $(document).ready(function () {
     $('.dropdown-toggle').dropdown();
     });
</script>
{% endblock %}
{% endblock content %}