company/company/urls.py
from django.contrib import admin
from django.urls import include,path
from .views import HomePageView
from django.views.generic.base import TemplateView # new
from django.conf import settings 
from django.conf.urls.static import static 

urlpatterns = [
    # display Custom Admin Login  page
    path('admin/', admin.site.urls),
    path('', HomePageView.as_view(),name='home'), # display home page 
    path('about/', TemplateView.as_view(template_name='about.html'), name='about'),  # display about page
    path('services/', TemplateView.as_view(template_name='services.html'), name='services'),  # display services page
    path('contact/', TemplateView.as_view(template_name='contact.html'), name='contact'),  # display contact page
    path('accounts/', include('accounts.urls'), name='accounts'),  # display Sign up page
    path('', include('employee.urls')),  # displays all employee app pages
]

if settings.DEBUG:
     urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

company/employee/urls.py
from django.urls import path
# importing views from views
from .views import EmployeeCreateViewOld,EmployeeListView,EmployeeDetailView,EmployeeUpdateView,EmployeeDeleteView, SignUpView



urlpatterns = [
    path('employee/create', SignUpView.as_view(), name='employee-create'),
    path('employees', EmployeeListView.as_view(), name='employees-list'),
    path('employee/<int:pk>/', EmployeeDetailView.as_view(), name='employee-detail'),
    path('employee/update/<int:pk>/', EmployeeUpdateView.as_view(), name='employee-update'),
    path('employee/delete/<int:pk>/', EmployeeDeleteView.as_view(), name='employee-delete'),


]

company/employee/models.py
# import the standard Django Model
# from built-in library
from django.db import models
from django.urls import reverse, reverse_lazy
from django.contrib.auth.models import User

# Create your models here.
# declare a new model with a name"employee"
class Employee(models.Model):
    # fields of the model
    eid = models.AutoField(primary_key=True,serialize = False,verbose_name ='ID')
    ename = models.CharField(max_length=100)
    eemail = models.EmailField()
    epassword = models.CharField(max_length=120, blank=True, null=True)
    econtact = models.CharField(max_length=15)
    edob = models.DateField(blank=True, null=True)# If no date is selected then Django  saves blank field value.

    def get_absolute_url(self):
        return reverse('employee-detail', kwargs={'pk': self.pk})
    #objects = models.Manager()
    class Meta:
        db_table = "employee"
        ordering = ['eid',]#sorts the records ascending using 'eid' field

class UserProfileDoc(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE)
    username = models.CharField(max_length=25,null=True)
    dob = models.DateField(blank=True,null=True)  # If no date is selected then Django saves blank field value.
    city = models.CharField(max_length=25,null=True)
    contactno = models.CharField(max_length=25,null=True)
    portfolio_site = models.URLField(blank=True,null=True)
    image = models.ImageField(null=True,upload_to='images/', default = 'images/None/no-img.jpg',blank=True)

company/employee/forms.py
from django import forms
from .models import Employee


# creating a form
class EmployeeForm(forms.ModelForm):
    edob = forms.DateField(widget=forms.TextInput(attrs=
    {
        'class': 'datepicker'
    }))

    
    # create meta class
    class Meta:
        # specify model to be used
        model = Employee

        fields = ['eid', 'ename', 'eemail', 'econtact', 'edob']

        #fields = '__all__'

       

       


       

        

company/employee/views.py
from django.urls import reverse_lazy
from django.views.generic import ListView
from django.contrib.auth.mixins import LoginRequiredMixin,UserPassesTestMixin
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from django.views.generic.detail import DetailView
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from .models import Employee, User
from accounts.models import UserProfileInfo
from accounts.forms import  UserCreateForm,UserProfileForm
# from .models import User,UserProfileInfo
# from .forms import UserProfileForm
from django.contrib.auth.models import User
from django.shortcuts import render
from django.views.generic import View
# from .forms import  UserCreateForm,UserProfileForm,LoginForm
from django.shortcuts import render,redirect 
from django.http.response import HttpResponseRedirect, HttpResponse

import pyautogui as pu


# Create your views here. 
class SignUpView(View):
    model = User,UserProfileInfo
    #login_url = reverse_lazy('login')
    form_class = UserCreateForm
    template_name = "signup.html"

    def get(self, request, *args, **kwargs):
        form = self.form_class()
        return render(request, self.template_name, {'form': form})


    def post(self, request, *args, **kwargs):
        form = UserCreateForm(request.POST, request.FILES or None)


        if form.is_valid():
            # Cleaned(normalized) data
            city = form.cleaned_data.get('city')
            contact_no = form.cleaned_data.get('contactno')
            date_of_birth = form.cleaned_data.get('dob')
            password = form.cleaned_data.get('password')
            username = form.cleaned_data.get('username')
            email = form.cleaned_data.get('email')
            firstname = form.cleaned_data.get('first_name')
            lastname = form.cleaned_data.get('last_name')
            confirm_password = form.cleaned_data.get('confirm_password')
            image = form.cleaned_data.get('image')


            # check if the password match
            if password == confirm_password:
                if not User.objects.filter(email=email).exists():


                    if  User.objects.filter(username=username).exists():
                        pu.alert("Username already exists.Registration Failed.Try again.")
                        return HttpResponseRedirect(reverse_lazy('employee/create'))
                        # return reverse_lazy('employees-list')
                    else:
                        new_user = User.objects.create_user(username=username, password=password, email=email,
                        first_name=firstname, last_name=lastname)
                        new_user.save()
                        user= User.objects.get(username=username)
                        p_form = UserProfileForm()
                        p_form = p_form.save(commit=False)
                        p_form.user = user
                        p_form.dob = date_of_birth
                        p_form.username=username
                        p_form.city = city
                        p_form.contactno = contact_no
                        p_form.image = image
                        p_form.save()
                        pu.alert( text="New User Created Successfully",title="Success")
                        # Create UserProfile model
                        return HttpResponseRedirect(reverse_lazy('employees-list'))

                        
                else:
                    pu.alert('Registration Failed - Try different email address')
                    return HttpResponseRedirect(reverse_lazy('employee/create'))
                # return HttpResponse('Form not valid')
                    # return reverse_lazy('employees-list')

            else:
                pu.alert("password and confirmpassword does not match.Try again")
                return HttpResponseRedirect(reverse_lazy('employee/create'))
        
        # return HttpResponse('Form not valid')

        else:
            pu.alert("Something went wrong.Try again")
            return HttpResponse('Form not valid')
            # return HttpResponseRedirect(reverse_lazy('employee/create')) 
    # return HttpResponseRedirect(reverse_lazy('employees-list')) 

# Only logged in superuser can see this view
class EmployeeCreateViewOld(LoginRequiredMixin,UserPassesTestMixin,CreateView):
    model = Employee
    template_name = "create.html"
    # template_name = "signup.html"
    fields=['eid','ename','eemail', 'epassword','econtact','edob']
    login_url = 'login'  #if not authenticated redirect to login page

    ''' model = UserProfileInfo
    template_name = "create.html"
    fields=['username'] '''
    
        

    # only superuser is allowed to see this view.
    def test_func(self):
        return self.request.user.is_superuser

    # url to redirect after successfully creation
    def get_success_url(self):
         #Displaying message of successful creation of new employee
         pu.alert(text='New Employee Created Successfully',title='Create',button='OK')
         return reverse_lazy('employees-list')


# Only logged in superuser can see this view
class EmployeeListView(LoginRequiredMixin,UserPassesTestMixin,ListView):

    model = Employee
    template_name = 'show.html'
    context_object_name = 'employees'
    paginate_by = 5
    login_url = 'login' #if not authenticated redirect to login page

    # only superuser is allowed to see this view.
    def test_func(self):
        return self.request.user.is_superuser


    def get_queryset(self):  # new

        if self.request.method == "GET":
            query = self.request.GET.get('search')  # your input name is 'search'
            print('Search word:' + str(query))
        if query:
            return Employee.objects.filter(ename__icontains=query)

        else:
            return Employee.objects.all()

    def get_context_data(self, **kwargs):
        context = super(EmployeeListView, self).get_context_data(**kwargs)
        employees = self.get_queryset()
        page = self.request.GET.get('page')
        paginator = Paginator(employees, self.paginate_by)
        try:
            employees = paginator.page(page)
        except PageNotAnInteger:
            employees = paginator.page(1)
        except EmptyPage:
            employees = paginator.page(paginator.num_pages)
        context['employees'] = employees
        return context



# Only logged in superuser can see this view
class EmployeeDetailView(LoginRequiredMixin,UserPassesTestMixin,DetailView):

    model = Employee
    template_name = 'detail.html'
    login_url = 'login' #if not authenticated redirect to login page

    # only superuser is allowed to see this view.
    def test_func(self):
        return self.request.user.is_superuser
   

# Only logged in superuser can see this view
class EmployeeUpdateView(LoginRequiredMixin,UserPassesTestMixin,UpdateView):
    model = Employee
    template_name = 'update.html'
    # specify the fields
    fields = ['eid', 'ename', 'eemail', 'econtact', 'edob']
    login_url = 'login' #if not authenticated redirect to login page

    # only superuser is allowed to see this view.
    def test_func(self):
        return self.request.user.is_superuser

    # updating details
    # url to redirect after successfully updation
    def get_success_url(self):
         # Displaying message of successful updation of  employee
         pu.alert(text='Employee Info Updated Successfully', title='Update', button='OK')
         return reverse_lazy('employees-list')



# Only logged in superuser can see this view
class EmployeeDeleteView(LoginRequiredMixin,UserPassesTestMixin,DeleteView):
    model = Employee
    template_name = 'delete.html'
    login_url = 'login' #if not authenticated redirect to login page

    # only superuser is allowed to see this view.
    def test_func(self):
        return self.request.user.is_superuser

    # url to redirect after successfully deletion
    def get_success_url(self):
        # Displaying message of successful deletion of employee
         pu.alert(text='Employee Deleted Successfully', title='Delete', button='OK')
         return reverse_lazy('employees-list')

company/employee/templates/create.html
{% extends 'base.html' %} {% block title %}
<title>Create Employee</title>
{% endblock title %} {% block content %}

<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
<link
  rel="stylesheet"
  href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css"
/>
<link rel="stylesheet" href="/resources/demos/style.css" />
<script src="https://code.jquery.com/jquery-1.12.4.js"></script>
<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>

<div class="container">
  <form method="POST" class="post-form">
    {% csrf_token %} {% comment %} {{ form.as_p }} {% endcomment %}
    <div class="container">
      <br />

      <div class="form-group row">
        <label class="col-sm-1 col-form-label"></label>
        <div class="col-sm-4">
          <h3>Create New Employee</h3>
          <h5>Enter New Employee Details</h5>
        </div>
      </div>

      <div class="form-group row">
        <label class="col-sm-2 col-form-label">Employee Name:</label>
        <div class="col-sm-4">{{ form.ename }}</div>
      </div>
      <div class="form-group row">
        <label class="col-sm-2 col-form-label">Employee Email:</label>
        <div class="col-sm-4">{{ form.eemail }}</div>
      </div>
      {% comment %} <div class="form-group row">
        <label class="col-sm-2 col-form-label">Employee Email:</label>
        <div class="col-sm-4">{{ form.username }}</div>
      </div> {% endcomment %}

      <div class="form-group row">
        <label class="col-sm-2 col-form-label">Password:</label>
        <div class="col-sm-4">{{ form.epassword}}</div>
      </div>

      <div class="form-group row">
        <label class="col-sm-2 col-form-label">Employee Contact:</label>
        <div class="col-sm-4">{{ form.econtact }}</div>
      </div>

      <div class="form-group row">
        <label class="col-sm-2 col-form-label">Date of Birth:</label>
        <div class="col-sm-4">
          {{ form.edob }}
          <i class="fa fa-calendar fa-lg"></i>
        </div>
      </div>

      <div class="form-group row">
        <label class="col-sm-2 col-form-label"></label>
        <div class="col-sm-4">
          <button type="submit" class="btn btn-info">Create</button>
          <a href="/employees" class="btn btn-info">Cancel</a>
        </div>
      </div>
    </div>
  </form>
</div>
{% block scripting %}
<script>
  $(function () {
    $("#id_edob").datepicker({
      changeMonth: true,
      changeYear: true,
      yearRange: "1950:2050",
      dateFormat: "yy-mm-dd",
      defaultDate: "24-09-2019",
    });
  });
</script>

<script>
  $(document).ready(function () {
    $(".dropdown-toggle").dropdown();
  });
</script>
{% endblock %} {% endblock content %}

company/employee/templates/delete.html
{% extends 'base.html' %}
{% block title %}
    <title>Delete Employee</title>
{% endblock title %}

{% block content %}

<script src ="https://code.jquery.com/jquery-3.3.1.min.js"></script>
<script src ="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
<script src ="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>

  <div class="container">
<form method="POST" class="post-form" >
        {% csrf_token %}
    <div class="text-danger">
                <h3><strong>Are you sure you want to delete employee id:{{ employee.eid  }}?</strong> </h3>
    </div>
    <div class="container">
<br>
    <div class="form-group row">
    <label class="col-sm-2 col-form-label"></label>
    <div class="col-sm-4">
    <h3>Employee Details</h3>
    </div>
  </div>

    <div class="form-group row">
    <label class="col-sm-3 col-form-label">Employee Id:</label>
    <div class="col-sm-4">
        <label>{{ employee.eid }} </label>
    </div>
  </div>

  <div class="form-group row">
    <label class="col-sm-3 col-form-label">Employee Name:</label>
    <div class="col-sm-4">
        <label>{{ employee.ename }} </label>
    </div>
  </div>

    <div class="form-group row">
    <label class="col-sm-3 col-form-label">Employee Email:</label>
    <div class="col-sm-4">
        <label>{{ employee.eemail }} </label>
    </div>
  </div>

    <div class="form-group row">
    <label class="col-sm-3 col-form-label">Employee Contact:</label>
    <div class="col-sm-4">
         <label>{{ employee.econtact }} </label>
    </div>
    </div>

   <div class="form-group row">
    <label class="col-sm-3 col-form-label">Employee Date of Birth:</label>
    <div class="col-sm-4 ">
         <label>{{ employee.edob }} </label>
    </div>
  </div>
  <div class="form-group row">
    <label class="col-sm-1 col-form-label"></label>
    <div class="col-sm-4">
    <button type="submit" class="btn btn-danger"><i class="fa fa-trash" style="font-size:24px;color:white"></i>Delete</button>
    <a href="/employees" class="btn btn-info">
        <span class="glyphicon glyphicon-arrow-left"></span>Cancel</a>
    </div>
  </div>

    </div>

</form>
 </div>
{% block scripting %}
<script>
   $(function () {
    $("#id_edob").datetimepicker({
        timepicker:false,
        datepicker:true,
        format:"Y-m-d", //Date format
        value:"2000-8-1", //default Date
        todayHighlight: true,
        autoclose: true,
        weeks:false
     })

     });
 </script>

 <script>
     $(document).ready(function () {
     $('.dropdown-toggle').dropdown();
     });
</script>
{% endblock %}

{% endblock content %}

company/employee/templates/detail.html
<{% extends 'base.html' %}
{% block title %}
    <title>Detail</title>
{% endblock title %}

{% block content %}

<script src ="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>

  <div class="container">

    <div class="container">
<br>
    <div class="form-group row">
    <label class="col-sm-2 col-form-label"></label>
    <div class="col-sm-4">
    <h3>Employee Details</h3>
    </div>
  </div>

    <div class="form-group row">
    <label class="col-sm-3 col-form-label">Employee Id:</label>
    <div class="col-sm-4">
        <label>{{ employee.eid }} </label>
    </div>
  </div>

  <div class="form-group row">
    <label class="col-sm-3 col-form-label">Employee Name:</label>
    <div class="col-sm-4">
        <label>{{ employee.ename }} </label>
    </div>
  </div>

    <div class="form-group row">
    <label class="col-sm-3 col-form-label">Employee Email:</label>
    <div class="col-sm-4">
        <label>{{ employee.eemail }} </label>
    </div>
  </div>

    <div class="form-group row">
    <label class="col-sm-3 col-form-label">Employee Contact:</label>
    <div class="col-sm-4">
         <label>{{ employee.econtact }} </label>
    </div>
    </div>

   <div class="form-group row">
    <label class="col-sm-3 col-form-label">Employee Date of Birth:</label>
    <div class="col-sm-4 ">
         <label>{{ employee.edob }} </label>
    </div>
  </div>
  <div class="form-group row">
    <label class="col-sm-1 col-form-label"></label>
    <div class="col-sm-4">

    <a href="/employees" class="btn btn-info">OK</a>
    </div>
  </div>

    </div>


 </div>
{% block scripting %}

 <script>
     $(document).ready(function () {
     $('.dropdown-toggle').dropdown();
     });
</script>
{% endblock %}

{% endblock content %}

company/employee/templates/show.html
{% extends 'base.html' %}
{% block title %}
    <title>Employee Manager</title>
{% endblock title %}

{% block content %}
<link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
<script src ="https://code.jquery.com/jquery-3.3.1.min.js"></script>
<script src ="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>


<body>

<center><h1>Employee Management System</h1></center></br>
<center><h2>Employees</h2></center>


<!-- search by name -->
<form class="form-inline" method="GET" >
        {% csrf_token %}
    <div class="input-group input-focus">
  <div class="input-group-prepend">
    <span class="input-group-text bg-white"><i class="fa fa-search"></i></span>
  </div>
  <input type="search" placeholder="Search by name part" name="search"   id="txtSearch" class="form-control border-left-0">
</div>


  <button type="submit" class="btn btn-success">Search</button>
</form>


<table class="table table-striped table-bordered table-sm">

    <thead class="thead-dark">
    <tr>
        <th>Employee ID</th>
        <th>Employee Name</th>
        <th>Employee Email</th>
        <th>Employee Contact</th>
        <th>Date of Birth</th>
        <th>Actions</th>
    </tr>
    </thead>
    <tbody>
{% for employee in employees %}
    <tr>
        <td>{{ employee.eid }}</td>
        <td>{{ employee.ename }}</td>
        <td>{{ employee.eemail }}</td>
        <td>{{ employee.econtact }}</td>
        <td>{{ employee.edob |date:"jS F Y" }}</td>
        <td>
            <a href="employee/{{ employee.eid }}"  class="view" title="View" data-toggle="tooltip"><i class="material-icons" style="color:brown">&#xE417;</i></a>
            <a href="employee/update/{{ employee.eid }}"  class="edit" title="Edit" data-toggle="tooltip"><i class="material-icons" style="color:blue">&#xE254;</i></a>

            <a href="employee/delete/{{ employee.eid }}" class="delete" title="Delete" data-toggle="tooltip"><i class="material-icons" style="color:red">&#xE872;</i></a>
        </td>



    </tr>
{% empty %}
<tr align="center" style="color:#FF0000"><td><b>No results to show.</b></td></tr>
{% endfor %}

    </tbody>
</table>

<!--Pagination-->
      <div class="container p-4">
        <div class="pagination justify-content-center">
            <span class="step-links">
              {% if employees.has_previous %}
                  <a href="?page=1">&laquo; first</a>
                  <a href="?page={{ employees.previous_page_number }}">previous</a>
              {% endif %}

                <span class="current">
                    Page {{ employees.number }} of {{ employees.paginator.num_pages }}
                </span>

              {% if employees.has_next %}
                  <a href="?page={{ employees.next_page_number }}">next</a>
                  <a href="?page={{ employees.paginator.num_pages }}">last &raquo;</a>
              {% endif %}
            </span>
            </div>
        </div>
      <!--end of Pagination-->
<br>
<br>
<center>
<a href="employee/create" class="btn btn-primary">Add New</a>
<a href="employees" class="btn btn-success">Show All</a>
</center>

</body>
{% block scripting %}

 <script>
     $(document).ready(function () {
     $('.dropdown-toggle').dropdown();
     });
</script>
{% endblock %}
{% endblock content %}

company/employee/templates/signup.html
{% extends 'base.html' %}
{% block title %}
    <title>SignUp</title>
{% endblock title %}

{% block content %}

  <script src ="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
  <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
  <link rel="stylesheet" href="/resources/demos/style.css">
  <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
  <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>



    <div class="container">
      <form method="POST" class="post-form" enctype="multipart/form-data">
        {% csrf_token %}
    <div class="container">
    <br>

    <div class="form-group row">
    <label class="col-sm-1 col-form-label"></label>
    <div class="col-sm-4">
    <h3>Create new user</h3>
    </div>
    </div>
    <!--    {{ form.errors }}
{{ form.non_field_errors }}-->

  <div class="form-group row">
    <label class="col-sm-2 col-form-label">UserName:</label>
    <div class="col-sm-4">
      {{ form.username }}
    </div>
  </div>


    <div class="form-group row">
    <label class="col-sm-2 col-form-label">First Name:</label>
    <div class="col-sm-4">
      {{ form.first_name}}
    </div>
  </div>

    <div class="form-group row">
    <label class="col-sm-2 col-form-label">Last Name:</label>
    <div class="col-sm-4">
      {{ form.last_name }}
    </div>
    </div>


    <div class="form-group row">
    <label class="col-sm-2 col-form-label">Email:</label>
    <div class="col-sm-4">
      {{ form.email }}
    </div>
    </div>

    <div class="form-group row">
    <label class="col-sm-2 col-form-label">Password:</label>
    <div class="col-sm-4">
      {{ form.password}}
    </div>
    </div>

    <div class="form-group row">
    <label class="col-sm-2 col-form-label">ConfirmPassword:</label>
    <div class="col-sm-4">
      {{ form.confirm_password}}
    </div>
    </div>

    <div class="form-group row">
    <label class="col-sm-2 col-form-label">City:</label>
    <div class="col-sm-4">
      {{ form.city}}
    </div>
    </div>

    <div class="form-group row">
    <label class="col-sm-2 col-form-label">ContactNo:</label>
    <div class="col-sm-4">
      {{ form.contactno}}
    </div>
    </div>



    <div class="form-group row">
    <label class="col-sm-2 col-form-label">Date of Birth:</label>
    <div class="col-sm-4">
      {{ form.dob }}
        <i class="fa fa-calendar fa-lg"></i>
    </div>
    </div>

   <div class="form-group row">
    <label class="col-sm-2 col-form-label">Profile Picture:</label>
    <div class="col-sm-4">
      {{ form.image}}
    </div>
   </div>




    <div class="form-group row">
    <label class="col-sm-2 col-form-label"></label>
    <div class="col-sm-4">
    <button type="submit" class="btn btn-info">Create</button>
    <a href="/employees" class="btn btn-info">Cancel</a>
    </div>
    </div>

    </div>

</form>
    </div>
{% block scripting %}
<script>
  $( function() {
    $( "#id_dob" ).datepicker({
      changeMonth: true,
      changeYear: true,
      yearRange: '1950:2050',
      dateFormat: 'yy-mm-dd',
      defaultDate:"24-09-2019"
    });
  } );
</script>
 <script>
     $(document).ready(function () {
     $('.dropdown-toggle').dropdown();
     });
</script>
{% endblock %}
{% endblock content %}

company/employee/templates/update.html
{% extends 'base.html' %}
{% block title %}
    <title>Update Employee</title>
{% endblock title %}

{% block content %}


<script src ="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
  <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css"> 
  <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
  <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>


    <div class="container">
      <form method="POST" class="post-form" >
        {% csrf_token %}
      {% if form.errors %}
	<!-- Error messaging -->
	<div id="errors">
		<div class="inner">
			<p>There were some errors in the information you entered. Please correct the following:</p>
			<ul>
				{% for field in form %}
					{% if field.errors %}<li>{{ field.label }}: {{ field.errors|striptags }}</li>{% endif %}
				{% endfor %}
			</ul>
		</div>
	</div>
	<!-- /Error messaging -->
{% endif %}

    <div class="container">


<br>
    <div class="form-group row">
    <label class="col-sm-1 col-form-label"></label>
    <div class="col-sm-4">
    <h3>Update Details</h3>
    </div>
  </div>


  <div class="form-group row align-items-center">
    <label for="id_ename" class="col-sm-2 col-form-label">Employee Name:</label>
    <div class="col-sm-4">
     <input type="text"  name="ename" id="id_ename"  required maxlength="25" value="{{ employee.ename }}" />
    </div>
  </div>

  <div class="form-group row align-items-center">
    <label for="id_eemail" class="col-sm-2 col-form-label">Employee Email:</label>
    <div class="col-sm-4">
     <input type="email"  name="eemail" id="id_eemail"  required maxlength="25" value="{{ employee.eemail }}" />
    </div>
  </div>

  <div class="form-group row align-items-center">
    <label for="id_econtact" class="col-sm-2 col-form-label">Employee Contact:</label>
    <div class="col-sm-4">
     <input type="text" name="econtact" id="id_econtact" required maxlength="15" value="{{ employee.econtact }}" />
    </div>
  </div>


   <div class="form-group row align-items-center">
   <label for="id_edob" class="col-sm-2 col-form-label">Date of Birth:</label>
    <div class="col-sm-8  pull-left">
       <input type="text" name="edob" id="id_edob" required maxlength="35" value="{{ employee.edob }}" aria-describedby="textHelpInline" >

     <span class="input-group-addon"><i class="fa fa-calendar fa-lg"></i></span>
    <big id="textHelpInline" class="text-muted">
        Date Must be YYYY-MM-DD Format.
    </big>
    </div>
  </div>


    <div class="form-group row">
    <label class="col-sm-2 col-form-label"></label>
    <div class="col-sm-4">
    <button type="submit" class="btn btn-info">Update</button>
    <a href="/employees" class="btn btn-info">Cancel</a>

    </div>
    </div>

    </div>

</form>
    </div>
{% block scripting %}
<script>
  $( function() {
    $( "#id_edob" ).datepicker({
      changeMonth: true,
      changeYear: true,
      yearRange: '1950:2050',
      dateFormat: 'yy-mm-dd',
      defaultDate:'2019-06-08'
    });
  } );
</script>

 <script>
     $(document).ready(function () {
     $('.dropdown-toggle').dropdown();
     });
</script>
<script>
            {% if messages %}
                {% for message in messages %}
                    alert(message);
                {% endfor %}
            {% endif %}
        </script>
{% endblock %}

{% endblock content %}